drivername = "postgresql+psycopg2" # driver name for the database
database = "postgres" # database name
username = "postgres" # username associated with the database
password = "root"
host = "localhost" # host address
port = "5432" # port required for connection