[sources.sql_database.credentials]
drivername = "postgresql+psycopg2" # driver name for the database
database = "university" # database name
username = "root" # username associated with the database
password = "root"                 
host = "localhost" # host address
port = "5432" # port required for connection